### ISSUE TITLE
Multithreaded version using concurrentqueue

### ISSUE THREAD

**Issue by atsushieno** [cjappl/rtlog-cpp#14]
I noticed that rtlog-cpp currently uses [readerwriterqueue](https://github.com/cameron314/readerwriterqueue) which would be efficient but only useful in single-reader-single-writer usage scenarios. It may be still useful in single-threaded audio plugins but not when multiple threads try to write. I'm using it in a host app where multiple threads could try to write logs, so I guess the current version is not appropriate for it.

I created [an experimental version](https://github.com/atsushieno/rtlog-cpp/tree/concurrent-queue) with [concurrentqueue](https://github.com/cameron314/concurrentqueue) and so far it seems working (although I have no heavy stress tests).

But I'm not much into this kind of stuff and maybe there are some overlooks that it may not be feasible. Is there any design choice on picking readerwriterqueue, if not performance reason? If mine seems useful I would happy to contribute here (but probably need some kind of optional flags to switch implementation).

**Comment by cjappl** [comment]
Hi @atsushieno 

The reason that this uses readerwriterqueue and not concurrentqueue is because RWQ is single producer single consumer. A SPSC queue can be designed to be wait free on push.

CQ is multi-producer multi-consumer. There is no MPMC queue (that I know of) that is wait-free on push, so it can't be used in real-time code.

**Comment by atsushieno** [comment]
Ahh, somehow I had the impression that concurrentqueue does that kind of hard task. Thank you, I'll just close this then.

**Comment by cjappl** [comment]
To contradict myself a few hours later - apparently there are mpmc queues that are wait free on write

https://youtu.be/PoZAo2Vikbo?si=aLshHzJjvnFhpg77

Timestamp 21:27 or so shows the chart and has discussions about fifos generally.

If you can help me prove that concurrentqueue is wait free on write, and you want to write a patch to integrate it I would be happy to upstream it.

**Comment by atsushieno** [comment]
(I also noticed that #6 was actually about this, but let me reply here so far.)

I was actually working on another approach to use MPSC (that fills my need so far) using `choc::fifo::SingleReaderMultiWriterFIFO`. https://github.com/atsushieno/rtlog-cpp/tree/mpsc

I guess I can safely replace concurrentqueue with choc, but if it's better to make it customizable I can make it so (with another template argument maybe?).

**Comment by cjappl** [comment]
I do think that it is more accurate to use a MPSC for situations where you have multiple real-time threads logging. It seems extremely likely that you will only have one logging thread, so the Multiple Consumer part of the queue is unnecessary.

Let me ponder a bit how we would put this in the API. Glad you got a way to work around your problem for now.

**Comment by cjappl** [comment]
@atsushieno just a heads up that this CHOC MPSC uses locks, so it is not wait-free or lock-free. It was probably not designed for usage in the real-time thread.

https://github.com/Tracktion/choc/blob/2d5841318adb9276151a8f3ca029752285dd075c/containers/choc_SingleReaderMultipleWriterFIFO.h#L91-L101

**Comment by atsushieno** [comment]
Uh, oh, I somehow misread it and thought its locking only at reading. That's conceptually not likely :(
Okay, I could have just used farbot in the first place - https://github.com/atsushieno/rtlog-cpp/tree/farbot

It introduced a new constraint on the max message size though; farbot requires the size to be 2^n. I guess it is not very compelling.

**Comment by cjappl** [comment]
Yeah, farbot should be a good choice!

In regards to updating rtlog to using farbot (or any other queue), the problem I was considering this morning is "How do you design the API so that it is flexible enough to use any queue?"

I think this is a bit of a tricky one, and I'll have to give it more thought in the future. I think this will be a bit of work.
